name: Linux CMake

on: [push]

env:             
  VCPKG_BINARY_SOURCES : 'clear;nuget,GitHub,readwrite'  
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VCPKG_VERSION: '2020.11' 

jobs:

  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-20.04'] 
        include:
          - os: 'ubuntu-20.04'
            triplet: 'x64-linux'
            mono: 'mono'
            VCPKG_WORKSPACE: '/vcpkg_own'
    steps:       
    - uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Remove old vcpkg (windows)
      shell: 'bash'
      run: |
        df -h
        ls -la /mnt
        #sudo apt list --installed
        mount 
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "pr.ref = ${{github.event.pull_request.head.ref}}"
          echo "github.ref   = ${{ github.ref }}"
          echo "github.actor = ${{ github.actor }}"
          echo "$GITHUB_CONTEXT"
          # mv  $VCPKG_INSTALLATION_ROOT c:/vcpkg_unused
     
    - name: Installing vcpkg
      if: steps.vcpkgcache.outputs.cache-hit != 'true'
      shell: 'bash'
      run: |
        cmake -E make_directory ${{ matrix.VCPKG_WORKSPACE }}
        cd ${{ matrix.VCPKG_WORKSPACE }}
        git clone -b '${{env.VCPKG_VERSION}}' --single-branch --depth 1 https://github.com/microsoft/vcpkg 
        ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
        ${{ matrix.VCPKG_WORKSPACE }}/vcpkg/vcpkg version
